export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const SET_INFO_MESSAGE = 'SET_INFO_MESSAGE';
export const SET_ALERT_MESSAGE = 'SET_ALERT_MESSAGE';
export const SET_FETCHING_REQUEST = 'SET_FETCHING_REQUEST';
export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const SET_USER = 'SET_USER';
export const SET_TOTP = 'SET_TOTP';

export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMON_BY_NAME_SUCCESS = 'GET_POKEMON_BY_NAME_SUCCESS';
export const SET_POKEMON = 'SET_POKEMON';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_ROWS_PER_PAGE = 'CHANGE_ROWS_PER_PAGE';
export const RESET_POKEMON = 'RESET_POKEMON';
